apiVersion: v1
kind: Service
metadata:
  name: chat-frontend-svc
  namespace: chat-stage
  labels:
    app: chat-frontend
    environment: stage
spec:
  type: NodePort
  selector:
    app: chat-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010
      protocol: TCP
