apiVersion: v1
kind: Service
metadata:
  name: chat-backend-svc
  namespace: chat-prod
  labels:
    app: chat-backend
    environment: prod
spec:
  type: ClusterIP
  selector:
    app: chat-backend
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
